version: '2.1'

services:
  auth: 
    image: nginx:latest
    container_name: production_nginx
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 8080:80
      - 4433:443
    networks:
      - mynet 
  app:
    image: app-service-basic-auth:${Build.BuildId}
    container_name: nodeapp
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - mynet
 
networks:
    mynet: